# This is the Apache config file for MCC.

# 6/23/2016 -- Etag security issue fix

WSGIApplicationGroup %{GLOBAL}

LoadModule wsgi_module "/usr/lib64/httpd/modules/mod_wsgi-py38.cpython-38m-x86_64-linux-gnu.so"

<IfModule !rewrite_module>
    loadmodule rewrite_module modules/mod_rewrite.so
</IfModule>
RewriteEngine on
RewriteCond %{REQUEST_METHOD} ^(TRACE|TRACK)
RewriteRule .* - [F]
FileETag MTime Size

<IfModule mod_headers.c>
    Header always edit Set-Cookie (.*) "$1; HttpOnly; Secure."
</IfModule>


#Specify the threads and processes that will be assigned to the MCC app. Since large files take a long time to upload, it's probably best to keep the timeout fairly high.
WSGIDaemonProcess mcc processes=3 threads=5 inactivity-timeout=120
WSGIProcessGroup mcc
#Map the location of the checker.wsgi script to the desired external location. In this case it's mapped to http://localhost/mcc

WSGIScriptAlias / /var/www/html/mcc/checker.wsgi
#Set permissions for the MCC directory
<Directory /var/www/html/mcc>
Order allow,deny
Allow from all
LimitRequestBody 15737418240
</Directory>

<Directory /usr/share/httpd/icons>
Deny from all
</Directory>

TimeOut 600

# Set limit on file upload size (in bytes) when submitting directly to the REST API.
# This also limits the size of any uncompressed gzip and bzip files.
SetEnv ApiMaxFileSize ${api_maxfilesize}

# Set limit on file upload size (in bytes) when submitting via the Web frontend.
SetEnv UiMaxFileSize ${ui_maxfilesize}

# Set the URL to redirect to the MCC main page
SetEnv HomepageURL ${mcc_homepage}

# Set the location to write temporary files to
SetEnv TempFileLocation ${tempfilelocation}

# Assign the venue displayed on the MCC homepage
SetEnv Venue ${venue}

# Set the envvar the compliance-checker package looks for to override the default standard names table
SetEnv CF_STANDARD_NAME_TABLE ${cfStandardNameTable}
