# This should be the URL of the MCC homepage
Define mcc_homepage "http://localhost:81/"

# This sets the maximum allowable upload size in bytes for the Flask app
Define api_maxfilesize "10737418240"

# This sets the maximum allowable upload size in bytes for the Webpage frontend
define ui_maxfilesize "5500000000"

# This sets the internal container location of the temporary files. It's generally not necessary to change this.
Define tempfilelocation "/tmp/mcc"

# This should be set to the name of the venue MCC is deployed to
Define venue "MCC"

# Defines the location of the CF standard name table to use with the CF checker,
# regardless of which CF version is utilized. Note this path should be relative
# to the MCC code location within the built container.
Define cfStandardNameTable "/var/www/html/mcc/utils/cf-standard-name-table-90.xml"
